AlunoApp/urls.py
from django.urls.conf import path, re_path

from . import views


app_name = 'AlunoApp'

urlpatterns = [
    path('', views.IndexTemplateView.as_view(), name='index'),
    re_path(r'^ajax/(?P<json>\w+|)/$', views.AjaxTemplateView.as_view(), name='ajax'),

    re_path(r'^listar/aluno/$', views.AlunoListView.as_view(), name='listar-aluno'),
    re_path(r'^cadastrar/aluno/$', views.AlunoCreateView.as_view(), name='cadastrar-aluno'),
    re_path(r'^alterar/aluno/(?P<pk>\w+|)/$', views.AlunoUpdateView.as_view(), name='alterar-aluno'),
    re_path(r'^excluir/aluno/(?P<pk>\w+|)$', views.AlunoDeleteView.as_view(), name='excluir-aluno'),

    re_path(r'^listar/turma/$', views.TurmaListView.as_view(), name='listar-turma'),
    re_path(r'^cadastrar/turma/$', views.TurmaCreateView.as_view(), name='cadastrar-turma'),
    re_path(r'^alterar/turma/(?P<pk>\w+|)/$', views.TurmaUpdateView.as_view(), name='alterar-turma'),
    re_path(r'^excluir/turma/(?P<pk>\w+|)/$', views.TurmaDeleteView.as_view(), name='excluir-turma'),

    re_path(r'^listar/aluno/turma/$', views.AlunoTurmaListView.as_view(), name='listar-aluno-turma'),
    re_path(r'^cadastrar/aluno/turma/$', views.AlunoTurmaCreateView.as_view(), name='cadastrar-aluno-turma'),
    re_path(r'^excluir/aluno/turma/(?P<pk>\w+|)$', views.AlunoTurmaDeleteView.as_view(), name='excluir-aluno-turma'),

]

DjangoProject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.static import serve
from AlunoApp import views as aluno_views

app_name = 'DjangoProject'

urlpatterns = [
    path('DjangoProject/admin/', admin.site.urls),
    path('DjangoProject/AlunoApp/', include('AlunoApp.urls')),

    path('DjangoProject/', aluno_views.IndexTemplateView.as_view(), name='index'),
    path('', aluno_views.IndexTemplateView.as_view(), name='index'),
]

AlunoApp/models.py
from django.db import models
from django.db.models.deletion import DO_NOTHING
from simple_history.models import HistoricalRecords
from django.dispatch.dispatcher import receiver
from os.path import os
from cpf_field.models import CPFField
import datetime
import uuid

# Create your models here.
class Aluno(models.Model):
    nome = models.CharField(max_length=250)
    cpf = CPFField(max_length=11, verbose_name='CPF')
    telefone_um = models.CharField(max_length=15, verbose_name='Telefone')
    telefone_dois = models.CharField(max_length=15, verbose_name='Outro Telefone', blank=True, null=True)
    logradouro = models.CharField(max_length=250, verbose_name='Endereço', blank=False, null=False)
    numero = models.IntegerField(max_length=8, verbose_name='Nº', blank=True, null=True)
    complemento = models.CharField(max_length=160, verbose_name='Complemento', blank=True, null=True)
    cidade = models.CharField(max_length=100, verbose_name='Cidade', blank=False, null=False)
    email = models.CharField(verbose_name='Email', max_length=100)
    ativo = models.BooleanField(verbose_name='Aluno está Devidamente ativo', )
    historico = HistoricalRecords()
    data_alteracao = models.DateTimeField(blank=True, null=True, verbose_name='Data de alteração:')
    data_cadastro = models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro:')
    #criado_por = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING, related_name='criado_por')
    

    class Meta:
        db_table = 'alunoapp_estudantes'

    def __str__(self):
        return self.nome

class Turma(models.Model):
    DIA_LST = (
        ('1','Segunda'),
        ('2','Terça'),
        ('3','Quarta'),
        ('4','Quinta'),
        ('5','Sexta'),
    )
    MATERIA_LST = (
        ('1','Português'),
        ('2','Matemática'),
        ('3','Ciências'),
        ('4','Artes'),
        ('5','Educação Física'),
    )
    nome = models.CharField(max_length=250)
    materia = models.CharField(max_length=1, null=False, blank=False, choices=MATERIA_LST)
    dia_semana = models.CharField(max_length=1, null=False, blank=False, choices=DIA_LST)
    hora_inicio = models.TimeField(blank=True, null=True)
    hora_termino = models.TimeField(blank=True, null=True)
    data_alteracao = models.DateTimeField(blank=True, null=True, verbose_name='Data de alteração:')
    data_cadastro = models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro:')
    #criado_por = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING, related_name='criado_por')

    class Meta:
        db_table = 'alunoapp_turma'

    def __str__(self):
        return self.nome

class AlunoTurma(models.Model):

    turma = models.ForeignKey(Turma, on_delete=models.DO_NOTHING, db_column='turma')
    aluno = models.ForeignKey(Aluno, on_delete=models.DO_NOTHING, db_column='aluno')
    data_cadastro = models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro:')
    #criado_por = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING, related_name='criado_por')

    class Meta:
        db_table = 'alunoapp_aluno_turma'

AlunoApp/forms.py
import datetime

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Field, Submit, Row, HTML, Fieldset, ButtonHolder
from crispy_forms.templatetags.crispy_forms_field import css_class
from django import forms
from django.db.models import Q
from django.forms.widgets import Select, CheckboxSelectMultiple, SelectMultiple, RadioSelect, ClearableFileInput
from django_summernote.widgets import SummernoteWidget
# from usuario.models import Usuario

from .models import Aluno, Turma, AlunoTurma

    
class AlunoForm(forms.ModelForm):

    class Meta:
        model = Aluno
        fields = '__all__'
        exclude = ['data_alteracao',]


class TurmaForm(forms.ModelForm):
    
    class Meta:
        model = Turma
        fields = '__all__'
        exclude = ['data_alteracao',]

    def __init__(self, *args, **kwargs):
        super(TurmaForm, self).__init__(*args, **kwargs)



class AlunoTurmaForm(forms.ModelForm):
    
    class Meta:
        model = AlunoTurma
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AlunoTurmaForm, self).__init__(*args, **kwargs)

AlunoApp/views.py
from io import BytesIO
from django.conf import settings
from django.core.paginator import Paginator
from django.core.files.storage import FileSystemStorage
from django.db import connections
from django.db.models import CharField, Value as V
from django.db.models.functions import Concat
from django.db.models.query_utils import Q
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.utils.dateparse import parse_date
from django.views.generic import ListView, CreateView
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView
from django.urls import reverse_lazy
import datetime
 
# from usuario.forms import UsuarioForm
# from usuario.models import Perfil, Sistema, Usuario, PerfilUsuario
# from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from . import forms
from .models import Aluno, Turma, AlunoTurma
from django.urls.base import reverse
from django.http.response import JsonResponse, HttpResponse
import json
from django.template.loader import render_to_string

# Create your views here.

class AjaxTemplateView(TemplateView):
    template_name = 'AlunoApp/ajax.html'

    def post(self, request, **kwargs):
        result = [{'foo': 1, 'bar': 2}]         
        return render(request, self.template_name, {'json': json.dumps(kwargs)})


class IndexTemplateView(TemplateView):
    template_name = 'AlunoApp/index.html'
    
    def get(self, request):
        
        
        return render(request, self.template_name, {'base': 'inicio'})

class AlunoListView(ListView):
    template_name = 'AlunoApp/listar-aluno.html'
    model = Aluno

    def get(self, request, **kwargs):
        aluno_lst = Aluno.objects.all().order_by('id')  
        
        return render(request, self.template_name, {'aluno_lst': aluno_lst})

class AlunoCreateView(CreateView):
    template_name = 'AlunoApp/cadastrar-aluno.html'

    def get(self, request):
        form = forms.AlunoForm
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = forms.AlunoForm(request.POST)
        if form.is_valid():
            formAluno = form.save(commit=False)
            # formAluno.criado_por = request.user            
            formAluno.save()
            form.save_m2m()
            
            success_url = reverse_lazy('AlunoApp:listar-aluno')
            return JsonResponse({'success': formAluno.id})
        else:
            return JsonResponse({'error': form.errors})

    def get_success_url(self):
        return reverse('AlunoApp:listar-aluno')

class AlunoUpdateView(UpdateView):
    model = Aluno
    form_class = forms.AlunoForm
    template_name = 'AlunoApp/alterar-aluno.html'
    context_object_name = 'aluno'

    def get(self, request, **kwargs):
        obj = get_object_or_404(Aluno, pk=kwargs.get('pk'))
        form = forms.AlunoForm(request.POST or None, instance = obj)
        this_aluno = Aluno.objects.get(pk=kwargs.get('pk'))
        return render(request, self.template_name, {'form': form, 'this_aluno': this_aluno})

    def get_success_url(self):
        return reverse('AlunoApp:ajax', kwargs={'json': 1})

    def post(self, request, *args, **kwargs):
        instance = get_object_or_404(Aluno, pk=kwargs.get('pk'))
        form = self.form_class(request.POST, instance = instance)
        if form.is_valid():
            formAluno = form.save(commit=False)
            formAluno.data_alteracao = datetime.datetime.now()  
            formAluno.save()
            return JsonResponse({'success': formAluno.pk})
        
    def get_context_data(self, **kwargs):
        context = super(AlunoUpdateView, self).get_context_data()
        return context

        
class AlunoDeleteView(DeleteView):
    model = Aluno
    success_url = reverse_lazy('AlunoApp:listar-aluno')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

class TurmaListView(ListView):
    template_name = 'AlunoApp/listar-turma.html'
    model = Turma

    def get(self, request, **kwargs):
        turma_lst = Turma.objects.all().order_by('id')  
        
        return render(request, self.template_name, {'turma_lst': turma_lst})

class TurmaCreateView(CreateView):
    template_name = 'AlunoApp/cadastrar-turma.html'

    def get(self, request):
        form = forms.TurmaForm
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = forms.TurmaForm(request.POST)
        if form.is_valid():
            formTurma = form.save(commit=False)       
            formTurma.save()
            form.save_m2m()
            
            success_url = reverse_lazy('AlunoApp:listar-turma')
            return JsonResponse({'success': formTurma.id})
        else:
            return JsonResponse({'error': form.errors})

    def get_success_url(self):
        return reverse('AlunoApp:listar-aluno')

class TurmaUpdateView(UpdateView):
    model = Turma
    form_class = forms.TurmaForm
    template_name = 'AlunoApp/alterar-turma.html'
    context_object_name = 'aluno'

    def get(self, request, **kwargs):
        obj = get_object_or_404(Turma, pk=kwargs.get('pk'))
        form = forms.TurmaForm(request.POST or None, instance = obj)
        this_turma = Turma.objects.get(pk=kwargs.get('pk'))
        return render(request, self.template_name, {'form': form, 'this_turma': this_turma})

    def get_success_url(self):
        return reverse('AlunoApp:ajax', kwargs={'json': 1})

    def post(self, request, *args, **kwargs):
        instance = get_object_or_404(Turma, pk=kwargs.get('pk'))
        form = self.form_class(request.POST, instance = instance)
        if form.is_valid():
            formTurma = form.save(commit=False)
            formTurma.data_alteracao = datetime.datetime.now()  
            formTurma.save()
            return JsonResponse({'success': formTurma.pk})
        
    def get_context_data(self, **kwargs):
        context = super(TurmaUpdateView, self).get_context_data()
        return context


class TurmaDeleteView(DeleteView):
    model = Turma
    success_url = reverse_lazy('AlunoApp:listar-turma')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class AlunoTurmaListView(ListView):
    template_name = 'AlunoApp/listar-aluno-turma.html'
    model = AlunoTurma

    def get(self, request, **kwargs):
        alunoturma_lst = AlunoTurma.objects.all().order_by('id')  
        
        return render(request, self.template_name, {'alunoturma_lst': alunoturma_lst})

class AlunoTurmaCreateView(CreateView):
    template_name = 'AlunoApp/cadastrar-aluno-turma.html'

    def get(self, request):
        form = forms.AlunoTurmaForm
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = forms.AlunoTurmaForm(request.POST)
        if form.is_valid():
            formAlunoTurma = form.save(commit=False)       
            formAlunoTurma.save()
            form.save_m2m()
            
            return JsonResponse({'success': formAlunoTurma.id})
        else:
            return JsonResponse({'error': form.errors})

    def get_success_url(self):
        return reverse('AlunoApp:listar-aluno')

class AlunoTurmaDeleteView(DeleteView):
    model = AlunoTurma
    success_url = reverse_lazy('AlunoApp:listar-aluno-turma')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

AlunoApp/templates/AlunoApp/ajax.html
{% for  j in json %}{{j}}{% endfor %}

AlunoApp/templates/AlunoApp/deletar-aluno.html
{% block conteudo %}
<html>
    <head>
		<meta charset="utf-8">
		<meta content="width=device-width, initial-scale=1.0" name="viewport">

		<title>CRUD Alunos - Deletar Estudante</title>
		<meta content="" name="description">
		<meta content="" name="keywords">

		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i' %}" rel="stylesheet">

		<!-- Bootstrap Simples -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		
        <!--  Datatables -->
		<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
		<script src=https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js></script>
        
	</head>
    <body>
        <form action='.'method='POST'>
            {% csrf_token %}
            <h1>Deseja realmente deletar este aluno {{aluno.nome}}?</h1>
            <p>
                <input type='submit' class="btn btn-warning" value='SIM' />
                <a href="{% url 'AlunoApp:listar-aluno' %}">
                    <button type="button" class="btn btn-danger excluir">NÃO</button>
                </a>
            </p>
            
        </form>
    </body>		
</html>  
{% endblock %}

{% block style %}
	<style>
		body{
			padding:5px;
			background-color:rgb(196, 221, 228);
			color:rgb(15, 2, 88) ;
		}
		#footer {
			position: fixed;
			height: 60px;
			bottom: 0px;
			left: 0px;
			right: 0px;
			margin-bottom: 0px;
		}
		a{
			text-decoration: none;
			color:black;
		}
		a:hover{
			color:rgb(55, 0, 255);
		}
		.btn-sm{
			padding:30px;
			height:160px;
			margin:0px 15px 0px 15px
		}
		.sm-h3{
			font-size: 1.6rem;
		}
        tr{
            background-color:white;
        }

	</style>
{% endblock %}

{% block scripts %}
{% endblock %}

AlunoApp/templates/AlunoApp/listar-aluno.html
{% block conteudo %}
<html>
    <head>
		<meta charset="utf-8">
		<meta content="width=device-width, initial-scale=1.0" name="viewport">

		<title>CRUD Alunos - Alunos</title>
		<meta content="" name="description">
		<meta content="" name="keywords">

		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i' %}" rel="stylesheet">

		<!-- Bootstrap Simples -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		
        <!--  Datatables -->
		<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
		<script src=https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js></script>
        
	</head>
    <body>
        <div class="col-md-12">
            <br>
            <a href="{% url 'AlunoApp:index' %}">
                <button type="button" class="btn btn-primary fa fa-file-o pull-left" id="index-btn">
                    Voltar à Home
                </button>
            </a>
            <a href="{% url 'AlunoApp:cadastrar-aluno' %}">
                <button type="button" class="btn btn-success fa fa-file-o pull-right" id="cmd-novo">
                    Cadastrar Estudante
                </button>
            </a>
            <br><br>
        </div>
        <br>
        <h1 class="text-center">Lista de Estudantes</h1>
        <br>
        {% csrf_token %}
        <table class="table table-bordered table-striped tabela-datatables" id="tabela-alunos">
            <thead>
                <tr>
                    <th class="text-center">Nome</th>
                    <th class="text-center">Cpf</th>
                    <th class="text-center">Telefones:</th>
                    <th class="text-center">Endereço:</th>
                    <th class="text-center">Cidade:</th>
                    <th class="text-center">Email:</th>
                    <th class="text-center">Ativo:</th>
                    <!-- <th class="text-center">Ultima Alteração:</th> -->
                    <th class="text-center">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for aluno in aluno_lst %}
                    <tr>
                        <td class="text-center">{{ aluno.nome }}</td>
                        <td class="text-center">{{ aluno.cpf }}</td>
                        <td class="text-center">{{ aluno.telefone_um }} {% if aluno.telefone_dois %} / {{aluno.telefone_dois}} {% endif %}</td>
                        <td class="text-center">{{ aluno.logradouro }}, {% if aluno.numero %} {{aluno.numero}}.{% else %}  S/N. {% endif %}{% if aluno.complemento %} {{aluno.complemento}}.{% endif %}</td>
                        <td class="text-center">{{ aluno.cidade }}</td>
                        <td class="text-center">{{ aluno.email }}</td>
                        <td class="text-center">{% if aluno.ativo %} Ativo {% else %} Inativo {% endif %}</td>
                        <!-- <td class="text-center">{% if aluno.data_alteracao %} Alterado em: {{ aluno.data_alteracao }} {% else %} Criado em: {{ aluno.data_cadastro }} {% endif %}</td> -->
                        <td class="text-center">
                            <a href="{% url 'AlunoApp:alterar-aluno' aluno.id %}">
                                <button type="button" class="btn btn-warning">Alterar</button>
                            </a>
                            <a href="{% url 'AlunoApp:excluir-aluno' aluno.id %}">
                                <button type="button" class="btn btn-danger">Excluir</button>
                            </a>
                        </td>
                        
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <br><br><br>
		<footer class="bg-light text-center text-lg-start" id="footer">
			<!-- Copyright -->
			<div class="row p-3" style="background-color: rgba(0, 0, 0, 0.2);">
				<div class="col-md-6 text-end">
					© 2022 | Guilherme Picoli dos Santos	
				</div>
				<div class="col-md-6 text-start">
					LinkedIn: <a href="https://www.linkedin.com/in/guipsantos/">@guipsantos</a>	
				</div>
			
			</div>
			<!-- Copyright -->
		</footer>
    </body>		
</html>  
{% endblock %}

{% block style %}
	<style>
		body{
			padding:5px;
			background-color:rgb(196, 221, 228);
			color:rgb(15, 2, 88) ;
		}
		#footer {
			position: fixed;
			height: 60px;
			bottom: 0px;
			left: 0px;
			right: 0px;
			margin-bottom: 0px;
		}
		a{
			text-decoration: none;
			color:black;
		}
		a:hover{
			color:rgb(55, 0, 255);
		}
		.btn-sm{
			padding:30px;
			height:160px;
			margin:0px 15px 0px 15px
		}
		.sm-h3{
			font-size: 1.6rem;
		}
        tr{
            background-color:white;
        }
        .pull-right{
            float:right;
            margin-right:20px;
        }
        .pull-left{
            float:left;
            margin-left:20px;
        }
	</style>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready( function () {
        $('#tabela-alunos').DataTable();
    //Onde o #myTable é o ID da tabela que você quer estilizar
    } );
</script>
{% endblock %}

AlunoApp/templates/AlunoApp/listar-turma.html
{% block conteudo %}
<html>
    <head>
		<meta charset="utf-8">
		<meta content="width=device-width, initial-scale=1.0" name="viewport">

		<title>CRUD Alunos - Turmas</title>
		<meta content="" name="description">
		<meta content="" name="keywords">

		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i' %}" rel="stylesheet">

		<!-- Bootstrap Simples -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		
        <!--  Datatables -->
		<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
		<script src=https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js></script>
        
	</head>
    <body>
        <div class="col-md-12">
            <br>
            <a href="{% url 'AlunoApp:index' %}">
                <button type="button" class="btn btn-primary fa fa-file-o pull-left" id="index-btn">
                    Voltar à Home
                </button>
            </a>
            <a href="{% url 'AlunoApp:cadastrar-turma' %}">
                <button type="button" class="btn btn-success fa fa-file-o pull-right" id="cmd-novo">
                    Cadastrar Turma
                </button>
            </a>
            <br><br>
        </div>
        <br>
        <h1 class="text-center">Lista de Estudantes</h1>
        <br>
        {% csrf_token %}
        <table class="table table-bordered table-striped tabela-datatables" id="tabela-turmas">
            <thead>
                <tr>
                    <th class="text-center">Materia</th>
                    <th class="text-center">Dia da Semana</th>
                    <th class="text-center">Início do Horário:</th>
                    <th class="text-center">Fim do Horário:</th>
                    <th class="text-center">Cadastro:</th>
                    <th class="text-center">Alteracao:</th>
                    <th class="text-center">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for turma in turma_lst %}
                    <tr>
                        <td class="text-center">{{ turma.get_materia_display }}</td>
                        <td class="text-center">{{ turma.get_dia_semana_display }}</td>
                        <td class="text-center">{{ turma.hora_inicio }}</td>
                        <td class="text-center">{{ turma.hora_termino }}</td>
                        <td class="text-center">{{ turma.data_cadastro }}</td>
                        <td class="text-center">{{ turma.data_alteracao}}</td>
                        <td class="text-center">
                            <a href="{% url 'AlunoApp:alterar-turma' turma.id %}">
                                <button type="button" class="btn btn-warning">Alterar</button>
                            </a>
                            <a href="{% url 'AlunoApp:excluir-turma' turma.id %}">
                                <button type="button" class="btn btn-danger">Excluir</button>
                            </a>
                        </td>
                        
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <br><br><br>
		<footer class="bg-light text-center text-lg-start" id="footer">
			<!-- Copyright -->
			<div class="row p-3" style="background-color: rgba(0, 0, 0, 0.2);">
				<div class="col-md-6 text-end">
					© 2022 | Guilherme Picoli dos Santos	
				</div>
				<div class="col-md-6 text-start">
					LinkedIn: <a href="https://www.linkedin.com/in/guipsantos/">@guipsantos</a>	
				</div>
			
			</div>
			<!-- Copyright -->
		</footer>
    </body>		
</html>  
{% endblock %}

{% block style %}
	<style>
		body{
			padding:5px;
			background-color:rgb(196, 221, 228);
			color:rgb(15, 2, 88) ;
		}
		#footer {
			position: fixed;
			height: 60px;
			bottom: 0px;
			left: 0px;
			right: 0px;
			margin-bottom: 0px;
		}
		a{
			text-decoration: none;
			color:black;
		}
		a:hover{
			color:rgb(55, 0, 255);
		}
		.btn-sm{
			padding:30px;
			height:160px;
			margin:0px 15px 0px 15px
		}
		.sm-h3{
			font-size: 1.6rem;
		}
        tr{
            background-color:white;
        }
        .pull-right{
            float:right;
            margin-right:20px;
        }
        .pull-left{
            float:left;
            margin-left:20px;
        }
	</style>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready( function () {
        $('#tabela-turmas').DataTable();
    //Onde o #myTable é o ID da tabela que você quer estilizar
    } );
</script>
{% endblock %}